function acprDb = computeACPR(x, fs, mainBw, offsetFactor)
%COMPUTEACPR Estimate ACPR by FFT integration of useful and adjacent channels.
%
%   computeACPR(x, fs, mainBw) uses the NORMATIVE geometry: the adjacent
%   window is one channel wide (mainBw) and centred one channel spacing away
%   (at mainBw from the carrier centre), i.e. it spans mainBw/2 to
%   3*mainBw/2. This matches the ACLR definition of 3GPP TS 38.104.
%
%   computeACPR(x, fs, mainBw, offsetFactor) shifts that window outwards by
%   offsetFactor*mainBw. This is a DELIBERATE departure from the normative
%   position, and the reason is measurement dynamic range, not convenience:
%   the OFDM waveform generated by this bench carries no per-symbol
%   windowing and no shaping filter, so its own spectral splatter reaches
%   -20.0 dBc at the normative position. The un-linearized PA output sits at
%   -14.5 dBc there, leaving barely 5.6 dB between "signal alone" and "PA
%   without DPD" -- too little for any predistorter effect to be resolved.
%   Measured values at increasing offsets (nominal S0 waveform):
%
%       offset      source      PA w/o DPD    usable range
%       0.00*BW    -20.3 dBc     -15.3 dBc       5.0 dB   (normative)
%       0.25*BW    -33.4 dBc     -20.3 dBc      13.1 dB
%       0.50*BW    -36.1 dBc     -24.6 dBc      11.5 dB
%
%   offsetFactor is therefore a bench parameter, set by cfg.acpr.offsetFactor
%   and reported as such. It must be stated whenever ACPR figures from this
%   bench are compared with a normative limit: at any offset the waveform
%   floor keeps the -45 dBc ACLR limit of TS 38.104 out of reach, so the
%   ACPR reported here is a RELATIVE indicator of spectral regrowth, not a
%   conformity measurement.
if nargin < 4 || isempty(offsetFactor)
    offsetFactor = 0;   % normative position by default
end
x = x(:);
if isempty(x), error('Input signal is empty.'); end
if any(~isfinite(real(x))) || any(~isfinite(imag(x)))
    error('Input contains NaN or Inf.');
end
Nfft = 2^nextpow2(max(4096, min(numel(x), 2^18)));
seg = x(1:min(numel(x), Nfft));
if numel(seg) < Nfft
    seg(end+1:Nfft) = 0;
end
w = hannLocal(Nfft);
X = fftshift(fft(seg(:).*w(:), Nfft));
P = abs(X).^2;
f = (-Nfft/2:Nfft/2-1).' * fs/Nfft;
lo = mainBw/2 + offsetFactor*mainBw;
hi = min(lo + mainBw, fs/2);
mainMask = abs(f) <= mainBw/2;
adjMask = (abs(f) > lo) & (abs(f) <= hi);
mainP = sum(P(mainMask));
adjP = sum(P(adjMask));
acprDb = 10*log10(max(adjP, realmin) / max(mainP, realmin));
end

function w = hannLocal(N)
n = (0:N-1).';
w = 0.5 - 0.5*cos(2*pi*n/(N-1));
end
