function row = summarizeMetrics(scenarioId, info, methodName, beforeMetrics, duringMetrics, afterMetrics, numAdapt, runtime_s, comments)
%SUMMARIZEMETRICS Create one table row for scenario summary.
%   Three time periods are reported: before (first third of the signal),
%   during (middle third, where drift develops) and after (last third).
row = table(string(scenarioId), string(info.waveform), string(info.modulation), info.bandwidth/1e6, getIBO(info), string(methodName), ...
    beforeMetrics.NMSE_dB, duringMetrics.NMSE_dB, afterMetrics.NMSE_dB, ...
    beforeMetrics.EVM_percent, duringMetrics.EVM_percent, afterMetrics.EVM_percent, ...
    beforeMetrics.ACPR_dBc, duringMetrics.ACPR_dBc, afterMetrics.ACPR_dBc, ...
    numAdapt, runtime_s, string(comments), ...
    'VariableNames', {'Scenario','Waveform','Modulation','Bandwidth_MHz','IBO_dB','Method', ...
    'NMSE_dB_before','NMSE_dB_during','NMSE_dB_after', ...
    'EVM_percent_before','EVM_percent_during','EVM_percent_after', ...
    'ACPR_dBc_before','ACPR_dBc_during','ACPR_dBc_after', ...
    'NumAdaptations','Runtime_s','Comments'});
end

function ibo = getIBO(info)
if isfield(info,'IBO_dB')
    ibo = info.IBO_dB;
else
    ibo = NaN;
end
end
